CREATE TABLE AreaPesquisa (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(100) NOT NULL
);

CREATE TABLE Projeto (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    titulo VARCHAR(200) NOT NULL,
    descricao TEXT NOT NULL,
    imagem VARCHAR(100) NOT NULL,
    categoria VARCHAR(20) NOT NULL
);

CREATE TABLE Publicacao (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    titulo VARCHAR(200) NOT NULL,
    link VARCHAR(200) NOT NULL
);

CREATE TABLE Orientacao (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    aluno VARCHAR(100) NOT NULL,
    trabalho VARCHAR(200) NOT NULL
);

CREATE TABLE MensagemContato (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(254) NOT NULL,
    assunto VARCHAR(100) NOT NULL,
    mensagem TEXT NOT NULL
);